_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
accelerator: "cpu"
devices: 1
max_epochs: 2

enable_model_summary: True
precision: "32-true"
limit_train_batches: 1.0
limit_val_batches: 1.0

# resume_from_checkpoint: null
#progress_bar_refresh_rate: 10

accumulate_grad_batches: 1
gradient_clip_val: 0

enable_checkpointing: True
