_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
accelerator: "gpu"
devices: 1
max_epochs: 12

enable_model_summary: True
precision: "bf16-mixed"
limit_train_batches: 1.0
limit_val_batches: 1.0
# resume_from_checkpoint: null

accumulate_grad_batches: 1
gradient_clip_val: 0

enable_checkpointing: False
