_target_: kplmb.models.transformer.RelationClassificationTransformer

id: PubMedBERT-base-uncased-abstract-fulltext
transformer: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext

optimized_metric: val/f1_epoch
lr: 3e-5
add_info_lr: null
max_length: 512
weight_decay: 0.0

use_cls_token: true
use_start_tokens: false
use_end_tokens: false
entity_marker: "SPECIAL_TOKEN"
use_norel_class: True
blind_entities: False
input_prompt: null
add_text_prompt: False
num_context_sentences: 0

use_xavier_init: False
